#TASK: use the genotype matrices created by viva to create heatmaps of the whole miRNAs (for the predicted miRNAs)
library(tidyverse)
source("C:/Users/cajus/OneDrive/Dokumente/Bildung/Studium/6. Semester/Bachelorarbeit/Code/Create heatmaps/functions.R")

positions <- read.table(file = "C:/Users/cajus/OneDrive/Dokumente/Bildung/Studium/6. Semester/Bachelorarbeit/Code/Predict miRNAs/Create heatmaps/regions_predicted_miRNAs.csv", header = TRUE, sep = ",")
#iterate over all miRNAs 
for(i in 1:length(positions$name)){
  #exclude the miRNAs for which 0 variants were identified (because no output was generated by VIVA)
  if(grepl(pattern = positions[i,"name"], x = "miR5642a|miR8167b|miR8167d|miR854d|miR854e|miR5630a|miR5630b|miR8167e")){
    next
  }
  #start positions of the different regions of the miRNA (when the miRNA starts at 1 and ends at length(miRNA))
  #we set the length of the base to 25bp
  base_one <- 1
  miRNA_one <- abs(positions[i, "miRNA_one"] - positions[i, "base_one"]) + 1
  loop <- abs(positions[i, "loop"] - positions[i, "base_one"]) + 1
  miRNA_two <- abs(positions[i, "miRNA_two"] - positions[i, "base_one"]) + 1
  base_two <- abs(positions[i, "base_two"] - positions[i, "base_one"]) + 1
  
  #read genotype matrix created by VIVA 
  matrix <- read.table(file = paste("C:/Users/cajus/OneDrive/Dokumente/Bildung/Studium/6. Semester/Bachelorarbeit/Code/Predict miRNAs/VIVA/results_all/", positions[i,1], "/Genotype_miRNA_positions_pred.vcf_matrix.csv", sep = ""), header = TRUE, sep = ",")  
  matrix <- matrix %>% separate(chr.position, into = c("chr", "pos"), sep = ",", convert = TRUE)
  #convert positions 
  matrix$pos <- abs(matrix$pos - positions[i, "base_one"]) + 1
  #create new matrix with all positions of the miRNA (rows) and all accessions (columns)
  matrix_all_positions <- matrix(data = NA, nrow = base_two + 24, ncol = ncol(matrix) - 2)
  #fill new matrix with the values of the genotype matrix
  for(x in 1:nrow(matrix)){
    matrix_all_positions[matrix$pos[x], ] <- as.numeric(matrix[x,3:ncol(matrix)])
  }
  
  name <- sub("mi", "MI", positions[i,1])
  #call function to create a heatmap
  create_heatmap(t(matrix_all_positions), base_one, miRNA_one, loop, miRNA_two, base_two, 0, 3, name, FALSE, colorscale = list(list(0.0, "white"), list(1/3, "lightblue"), list(2/3, "green"), list(1.0, "red")), path = "C:/Users/cajus/OneDrive/Dokumente/Bildung/Studium/6. Semester/Bachelorarbeit/Code/Predict miRNAs/Create heatmaps/heatmaps") 
}


#create heatmaps for the miRNAs for which no output was created by viva because no variants were detected
for(name in c("miR5642a","miR8167b","miR8167d","miR854d","miR854e","miR5630a","miR5630b","miR8167e")){
  i <- rownames(positions[positions$name == name, ])
  #start positions of the different regions of the miRNA (when the miRNA starts at 1 and ends at length(miRNA))
  #we set the length of the base to 25bp
  base_one <- 1
  miRNA_one <- abs(positions[i, "miRNA_one"] - positions[i, "base_one"]) + 1
  loop <- abs(positions[i, "loop"] - positions[i, "base_one"]) + 1
  miRNA_two <- abs(positions[i, "miRNA_two"] - positions[i, "base_one"]) + 1
  base_two <- abs(positions[i, "base_two"] - positions[i, "base_one"]) + 1
  
  #create new matrix with all positions of the miRNA (rows) and all accessions (columns)
  matrix_all_positions <- matrix(data = NA, nrow = base_two + 24, ncol = 1137 - 2)
  #add a dummy value (otherwise the creation of the heatmap does not work)
  matrix_all_positions[base_two + 24, 1135] <- 0
  
  name <- sub("mi", "MI", positions[i,1])
  #call function to create a heatmap
  create_heatmap(t(matrix_all_positions), base_one, miRNA_one, loop, miRNA_two, base_two, 0, 3, name, FALSE, colorscale = list(list(0.0, "white"), list(1/3, "lightblue"), list(2/3, "green"), list(1.0, "red")), path = "C:/Users/cajus/OneDrive/Dokumente/Bildung/Studium/6. Semester/Bachelorarbeit/Code/Predict miRNAs/Create heatmaps/heatmaps")
}


