#TASK: filter the csv files (with the information about the genotypes) created by viva and only keep 
#the variants with MAF (minor allel frequency) >= 0.005 and missing rate <= 0.5
library(tidyverse)

names <- read.table(file = "C:/Users/cajus/OneDrive/Dokumente/Bildung/Studium/6. Semester/Bachelorarbeit/Code/Predict miRNAs/Create heatmaps/regions_predicted_miRNAs.csv", header = TRUE, sep = ",")[,1]

for(name in names){
  #exclude the miRNAs for which 0 variants were identified (because no output was generated by VIVA)
  if(grepl(pattern = name, x = "miR5642a|miR8167b|miR8167d|miR854d|miR854e|miR5630a|miR5630b|miR8167e")){
    next
  }
  #read genotype matrix created by VIVA
  matrix <- read.table(file = paste("C:/Users/cajus/OneDrive/Dokumente/Bildung/Studium/6. Semester/Bachelorarbeit/Code/Predict miRNAs/VIVA/results_all/all/", name, "/Genotype_miRNA_positions_pred.vcf_matrix.csv", sep = ""), header = TRUE, sep = ",") 
  matrix <- matrix %>% separate(chr.position, into = c("chr", "pos"), sep = ",", convert = TRUE)
  #check for every variant (row) if MAF >= 0.005 and missing rate <= 0.5
  #meaning of the numbers in matrix: 0 = no data, 1 = homozygous reference, 2 = heterozygous variant, 3 = homozygous variant
  filtered <- matrix[rowMeans(matrix[ ,c(-1,-2)] == 3) >= 0.005 & rowMeans(matrix[ ,c(-1,-2)] == 0) <= 0.5, ]
  #save new matrix
  write.table(filtered, file = paste("C:/Users/cajus/OneDrive/Dokumente/Bildung/Studium/6. Semester/Bachelorarbeit/Code/Predict miRNAs/VIVA/results_all/filtered/", name, "_Genotype_MAF0.005_MR0.5_vcf.csv", sep = ""), quote = FALSE, sep = ",", row.names = FALSE)
}


